from __future__ import annotations

from .rules import (
    AtxHeading,
    Autolink,
    BackslashEscape,
    Blockquote,
    CharacterReference,
    Emphasis,
    ExtendedAutolink,
    FencedCode,
    Footnote,
    HardBreak,
    HtmlBlock,
    Image,
    IndentedCode,
    InlineCode,
    Link,
    List,
    RawHtml,
    SetextHeading,
    Strikethrough,
    Table,
    ThematicBreak,
)

GFM_DISALLOWED_HTML_TAGS = [
    'title',
    'textarea',
    'style',
    'xmp',
    'iframe',
    'noembed',
    'noframes',
    'script',
    'plaintext',
]

commonmark = [
    ThematicBreak,
    FencedCode,
    IndentedCode,
    HtmlBlock,
    List,
    AtxHeading,
    SetextHeading,
    Blockquote,
    HardBreak,
    Autolink,
    RawHtml,
    BackslashEscape,
    CharacterReference,
    Image,
    Link,
    InlineCode,
    Emphasis,
]

github = [
    Table,
    ThematicBreak,
    FencedCode,
    IndentedCode,
    HtmlBlock(disallowed_tags=GFM_DISALLOWED_HTML_TAGS),
    List(task=True),
    AtxHeading,
    SetextHeading,
    Blockquote,
    HardBreak,
    Autolink,
    RawHtml(disallowed_tags=GFM_DISALLOWED_HTML_TAGS),
    BackslashEscape,
    CharacterReference,
    Footnote,
    Image,
    Link,
    InlineCode,
    Strikethrough,
    Emphasis,
    ExtendedAutolink,
]
